### ISSUE TITLE
Восстановление личных данных пользователя

### ISSUE THREAD

**Issue by PaaavelZ** [Sanerins/tamtam-one-coffee-bot#19]
Сейчас в коде есть места (помеченные "TODO NULL_USER"), где нам приходит null'овый юзер и мы не знаем, что с ним делать. Есть идея завести с пользователем диалог и попросить его предоставить данные повторно, если такая возможность вообще есть (= есть айди юзера).

**Comment by Sanerins** [comment]
В большинстве мест реализовали такой функционал
